### ISSUE TITLE
Asset-admin toolbar icons breaking in mobile view

### ISSUE THREAD

**Issue by newleeland** [silverstripe/silverstripe-versioned#101]
Icons should be horizontal instead of vertically next to each other
![Screen_Shot_2018-01-31_at_11_45_57_AM.png](https://images.zenhubusercontent.com/596d365561b4ca3b0a74bd86/680ea4e5-0d85-466f-a250-67dd22570723)

**Comment by robbieaverill** [comment]
Issue moved to [silverstripe/silverstripe-asset-admin #729](https://github.com/silverstripe/silverstripe-asset-admin/issues/729) via [**ZenHub**](https://www.zenhub.com/)
