### ISSUE TITLE
Versioned dataobjects with ".versioned" not publishing $owns relations

### ISSUE THREAD

**Issue by diegopego86** [silverstripe/silverstripe-versioned#115]
I've created a dataobject with and Icon that is and Image object, i'm using the extention Versioned::class. 'versioned' instead of just Versioned::class as I don't want the dataobject to be Staged. I declared the $owns values and I'm expecting that the Image gets published when the object is saved but this is not happening. Here is what I have in my code:

```
    private static $has_one = [
        'Icon' => Image::class
    ];
    private static $extensions = [
      Versioned::class . '.versioned'
    ];

    private static $owns = [
        'Icon'
    ];
```

I've read something related to this but all the talk was in relation to Versioned::class and not the '.versioned': [https://github.com/silverstripe/silverstripe-framework/issues/7359](url)

# PRs:

 - [x] https://github.com/silverstripe/silverstripe-cms/pull/2102
 - [x] https://github.com/silverstripe/silverstripe-framework/pull/7878
 - [x] https://github.com/silverstripe/silverstripe-versioned/pull/120 (1.0)
 - [x] https://github.com/silverstripe/silverstripe-assets/pull/119
 - [x] https://github.com/silverstripe/silverstripe-versioned/pull/121 (1.1)

**Comment by chillu** [comment]
So you have a `MyObject` and `MyObject_Versions` table, but not a `MyObject_Live` table? If you don't have a separate Live table, records should effectively be published without copying it to a separate table. In that case, you're only using `Versioned` as a way to get an audit log of changes. What did you expect to happen in this case?

**Comment by diegopego86** [comment]
@chillu exactly, I just have `MyObject` and `MyObject_Versions` table. So yes I just added the reccord as a log for any changes the user have done. What I expect is that the Icon image uploaded to the MyObject gets published, what is happening is that when I save the object the image is added to my file but in Stage mode so I need to go to the Files Manager and find the image and then manually publish it.

**Comment by chillu** [comment]
@tractorcow Any ideas?

**Comment by diegopego86** [comment]
Hey guys, so I decided to run 2 tests on Silverstripe SS 4.0.3 and SS 4.1.0-rc2 of the same issue and here are my findings:

First this is the code for MyObject:

**mysite/code/dataobjects/MyObject.php**

```
<?php
use SilverStripe\Versioned\Versioned;
use SilverStripe\ORM\DataObject;
use SilverStripe\Assets\Image;

class MyObject extends DataObject 
{
    private static $db = [
        'Name' => 'Varchar(255)',
        'Sort' => 'Int'
    ];
    private static $has_one = [
        'Icon' => Image::class
    ];
    private static $default_sort = 'Sort ASC';
    private static $extensions = [
      Versioned::class . '.versioned' 
    ];
    
    private static $owns = [
        'Icon'
    ];    
}
```

Here is my Model Admin:

**mysite/code/admin/MyObjectAdmin.php**

```
<?php
use SilverStripe\Admin\ModelAdmin;

class MyObjectAdmin extends ModelAdmin 
{

    private static $managed_models = [
        'MyObject'
    ];
    private static $url_segment = 'my_object';

    private static $menu_title = 'MyObjects';
    
}

```

See how i'm using the extension `Versioned::class . '.versioned' ` instead of just `Versioned::class`.

First there are 2 main differences between SS 4.0.3 and SS 4.1.0-rc2 when you try to create an object from the admin, in 4.1.0-rc2 there is a Publish button in the footer, see the following image:

![Image of Silverstripe V4.0.3 v 4.1.0-rc2 and Versioned Dataobject creation](http://i65.tinypic.com/vysl7n.png)

If I press create in both version, the object is saved and the image is added, but the image is on Draft mode, I was expecting it to be Live as MyObject doesn't use Stage. See the image bellow:

![Image of Draft mode of image uploaded to silverstripe](http://i64.tinypic.com/2gwe62e.png)

Now, in Silverstripe 4.1.0-rc2 that there is a Publish button,if I press it, I get an Internal Server error:
![Image of internal server error on publish silverstripe 4.1.0-rc2](http://i66.tinypic.com/358di1j.png)

Checking my log I see that the error is because is trying to publish the dataobject to the _Live table that doesn't exists, here is part of the log message:

`[2018-02-19 15:22:52] error-log.ERROR: Uncaught Exception SilverStripe\ORM\Connect\DatabaseException: "Couldn't run query:  SELECT "Version" FROM "MyObject_Live" WHERE "ID" = ?  42S02-1146: Table 'ss_testsilverstripe4_1_0.myobject_live' doesn't exist" at /Users/.../silverstripe4.1.0/vendor/silverstripe/framework/src/ORM/Connect/DBConnector.php line 64 {"exception":"[object] (SilverStripe\\ORM\\Connect\\DatabaseException(code: 0): Couldn't run query:\n\nSELECT \"Version\"\nFROM \"MyObject_Live\"\nWHERE \"ID\" = ?\n\n42S02-1146: Table 'ss_testsilverstripe4_1_0.myobject_live' doesn't exist at /Users/.../silverstripe4.1.0/vendor/silverstripe/framework/src/ORM/Connect/DBConnector.php:64)"} []`

**Comment by tractorcow** [comment]
Yep this is a real bug. We have well tested unversioned as well as versioned + staged, but we haven't well tested versioned without staging.

**Comment by tractorcow** [comment]
Bunch of PR incoming.

**Comment by tractorcow** [comment]
Ok, main fix is at https://github.com/silverstripe/silverstripe-versioned/pull/121 for 1.1 branch, but I've updated all modules to properly respect unstaged versioned objects.

**Comment by diegopego86** [comment]
Hey guys, I've checked the changed made to the repo to fix the issue, I can see that now there is an "Apply Changes" instead of the "Create" and "Publish" buttons from before. There is also an info message "Draft/modified items will be published", but still when y click the button and the object is saved, the image is still in Draft mode.

I've checked that the current versions of my dev silvertripe environment are the ones updated with the changes:

-cms commit: 7e619da62af592dbe3a2940710c1c07b9412f763
-framework commit: 7fe8da3222b6e8cff66d185d4c4fd5e38aacf58e
-versioned commit: d365bbbd8441688e3521282b3d54ae1f12e096c1
-assets commit: 5b21410ddfb0e8dc6e17f778bf2785e5b15f261f

Is there anything I'm missing?

**Comment by tractorcow** [comment]
@diegopego86 sorry you may need to wait for us to merge up some of the 4.0 bugfixes into 4.1. I'll aim to get that to you by tomorrow.

**Comment by wernerkrauss** [comment]
I have a hard time, getting `owns` working with `Versioned::class . '.versioned'` applied in SS4.2.1

The code is https://github.com/wernerkrauss/ImageGallery/tree/migrating-to-ss4

It works without Versioned extension at all or with default stage/live Versioned extension.

Calling `publishSingle` on my relations manually as shown in https://forum.silverstripe.org/t/silverstripe-4-gotchas/61/5 works of course, but should not be needed when defining `owns`, should it?

**Comment by kinglozzer** [comment]
Sounds like this may have regressed

**Comment by bergice** [comment]
@wernerkrauss

I just checked out your library and it looks like you need to update the `$owns` on `ImageGalleryAlbum` to the following:

```
    private static $owns = [
        'CoverImage',
        'Folder',
        'GalleryItems'
    ];
```

Does this resolve your problem?

If not, could you give some more details on exactly what is not working?

**Comment by sanderha** [comment]
Hello,
Seems like this issue is back in 4.4.
Doing this:
```
NobrainerWeb\App\Tracks\Track:
  extensions:
    - SilverStripe\Versioned\Versioned.versioned
```
with this file relation and owns:
```
    private static $has_one = [
        'AudioFile' => File::class
    ];

    private static $owns = [
        'AudioFile'
    ];
```
When I add a file via the standard uploadfield and save the Track object, the AudioFile is always draft.

**Comment by ScopeyNZ** [comment]
> save the Track object

The `AudioFile` should only publish when you publish the `Track`. Can you confirm that's not working?
