### ISSUE TITLE
SS5: WasPublished seems broken

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-versioned#124]
silverstripe/cms:dev-master tests are failing because of an assumption about CSS classes that will be present in the history controller (specifically the `VersionsForm`).

It appears that all records, whether saved as draft or published come back with `WasPublished` being truthy and this means the wrong CSS classes are being applied and also that the `Show unpublished versions` checkbox does nothing.

# PRs:

 - [x] https://github.com/silverstripe/silverstripe-versioned/pull/141

**Comment by tractorcow** [comment]
It's not just master.

**Comment by tractorcow** [comment]
Ah no it is... separate issue .;)

**Comment by tractorcow** [comment]
Just needs a merge up.

Also, graphql 2.x has been retconned for framework 4.2 and above. framework 5 should now be using graphql 3.x.

**Comment by dhensby** [comment]
versioned seems to be all merged up...

**Comment by dhensby** [comment]
One of the CMS tests is passing that was failing, but still 2 failing: https://travis-ci.org/silverstripe/silverstripe-cms/builds/356924038

**Comment by tractorcow** [comment]
I haven't finished merging up. Only 1/2 way through the modules.

**Comment by tractorcow** [comment]
All merged up. :D

**Comment by tractorcow** [comment]
waiting for https://travis-ci.org/silverstripe/silverstripe-cms/builds/362334146 to build.

**Comment by tractorcow** [comment]
Well it's closer! Only one bug now, not a huge list of them.

**Comment by tractorcow** [comment]
```
1) SilverStripe\CMS\Tests\Controllers\CMSPageHistoryControllerTest::testVersionsFormTableContainsInformation
Failed asserting that 'even published' contains "internal".
```

Probably a mix of Versioned_Version being deprecated in 5.x and the WasDraft / WasDeleted change in 4.x not working together. Bugfix in 5.x IMO as a separate PR.

**Comment by tractorcow** [comment]
Additionally, fails with MySQLPDODatabase, but passes with MySQLDatabase

**Comment by tractorcow** [comment]
because DBString::exists() treats "0" string for "WasPublished" as true, when it's a boolean.

Fix: Cast WasPublished as boolean

**Comment by tractorcow** [comment]
```


    private static $casting = [
        "RecordID" => "Int",
        "Version" => "Int",
        "WasPublished" => "Boolean",
        "WasDeleted" => "Boolean",
        "WasDraft" => "Boolean",
        "AuthorID" => "Int",
        "PublisherID" => "Int",
    ];
    ```
    
    Fixes everything ;)

**Comment by tractorcow** [comment]
Pr at https://github.com/silverstripe/silverstripe-versioned/issues/124
