### ISSUE TITLE
Publishing a page now increments the version number

### ISSUE THREAD

**Issue by mikenz** [silverstripe/silverstripe-versioned#135]
A change introduced in the last week has changed the behaviour when publishing a page.

Previously publishing a page didn't increment the version number. If a page is currently version 4 and then it is published version 4 is published.

Now a new version is published. If a page is currently version 4 and then it is published a new version 5 is created and them published. This is unexpected and undesirable.

This shouldn't happen as there were no changes introduced between the versions. 

We also have failing tests around rollbacks double incrementing the version. Currently on version 3, roll back to version 1 and it's saved as version 5, not 4. I'm guessing this is the same root cause.

**Comment by mikenz** [comment]
Oh, seems this was deliberate?
https://github.com/silverstripe/silverstripe-versioned/pull/131/files#diff-6c456f2f920c475f0c35df6cb85dce4aR1363

**Comment by dhensby** [comment]
@unclecheese @tractorcow do you have any insight as to why this change was necessary?

**Comment by mikenz** [comment]
Raised the double incrementing as https://github.com/silverstripe/silverstripe-versioned/issues/136 that definitely shouldn't be happening.

**Comment by tractorcow** [comment]
The double increment seems sneaky but it's actually intentional also. :) The "missing" version is the new "WasDeleted" state we added to track deletions as well as modifications.

**Comment by tractorcow** [comment]
My comment at https://github.com/silverstripe/silverstripe-versioned/issues/136#issuecomment-375130040

> Yes this is intentional. Version history tracking now tracks not only changed pages, but also changed states, including being published / on draft. Restoring a page from history now results in a new state, and thus a new version number being assigned.

> You'll find that version 2 is tracked as the "deleted" state, which is unqueryable, but exists in the _Versioned table as a placeholder audit log for "this is when we deleted this record from draft".

> Is that particular row present in your _Versions table?
