### ISSUE TITLE
Backport "Select stage with explicit get param" to 3.x

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-versioned#145]
Original issue: https://github.com/silverstripe/silverstripe-cms/issues/1578
PRs for original issue:
 - https://github.com/silverstripe/silverstripe-framework/pull/7399
 - https://github.com/silverstripe/silverstripe-versioned/pull/45
 - https://github.com/silverstripe/silverstripe-admin/pull/467
 - https://github.com/silverstripe/silverstripe-cms/pull/2129

This should be opt-in for 3.x, since we can't rely on devs using the proper `Link()` methods to generate links in their responses - and changed default behaviour runs the risk of breaking draft previews on those implementations.

Check that this still works with the shareddraftcontent module.

# PRs:

 - [x] https://github.com/silverstripe/silverstripe-framework/pull/8026
 - [x] https://github.com/silverstripe/silverstripe-cms/pull/2153

**Comment by tractorcow** [comment]
I estimate this work at about 5 points, with the additional exclusions:

- FunctionalTest doesn't need to work with use_session = false.
- Given that RequestHandler has no Link() method in 3.x, it may be necessary for more modules to opt-in to stage url decoration. It will be less "out of the box" as it is in 4.x.

**Comment by tractorcow** [comment]
WIP PR at https://github.com/silverstripe/silverstripe-framework/pull/8026

**Comment by tractorcow** [comment]
Other pr https://github.com/silverstripe/silverstripe-cms/pull/2153

**Comment by tractorcow** [comment]
Ready to review!

**Comment by chillu** [comment]
I've kicked off a discussion with core committers on the forum if this should target 3.7.x or 3.6.x, there's a few support commitment complexities related to it. Please don't merge until we've resolved this.
