### ISSUE TITLE
SS4.1 Publish Recursive

### ISSUE THREAD

**Issue by nglasl** [silverstripe/silverstripe-versioned#153]
I noticed when jumping from SS4.0 to SS4.1 that my module tests started failing. Upon further investigation, it looks like `->publishRecursive()` isn't actually publishing my page (as it was in SS4.0). Changing this back to `->writeToStage('Live')` resolves the problem. So it seems there is a breaking change that was introduced in SS4.1. You can run the functional tests over on https://github.com/nglasl/silverstripe-misdirection to confirm this behaviour.

**Comment by maxime-rainville** [comment]
@nglasl Thanks for raising this issue. I tried running the test on your package, but couldn't get them running.

Any chance you could provide a simple code sample that used to work in SS4.0 and now breaks in SS4.1? That would make it easier to diagnose the issue.

**Comment by nglasl** [comment]
@maxime-rainville, cheers for the quick response. You just need to run `vendor/bin/phpunit vendor/nglasl/silverstripe-misdirection/tests/FunctionalTests.php`. Is that not working for you?

**Comment by maxime-rainville** [comment]
Sorry. I had to to park this one for while.

I just got the your unit test running with SilverStripe 4.1 and `$first` and `$second` got published for me.

Can you confirm, you are still seeing an issue on your end. It may have been fixed while working on something else.

**Comment by nglasl** [comment]
@maxime-rainville, just went to confirm but looks like I'm still having the same issue. Please see my versions below. Perhaps we should park this one until I can get Travis up and running on the module?

```
Installing silverstripe/cms (4.x-dev e1e92db)
Installing silverstripe/framework (4.x-dev 14784f0)
Installing nglasl/silverstripe-misdirection (dev-master 46b0179)
```

```
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.15-1+ubuntu16.04.1+deb.sury.org+2 with Xdebug 2.6.0
Configuration: /var/www/dynamic/testing/ss4/phpunit.xml

F                                                                   1 / 1 (100%)

Time: 7.7 seconds, Memory: 48.00MB

There was 1 failure:

1) nglasl\misdirection\tests\FunctionalTests::testRequestFilter
Failed asserting that 200 matches expected '301'.

/var/www/dynamic/testing/ss4/vendor/nglasl/silverstripe-misdirection/tests/FunctionalTests.php:101
/var/www/dynamic/testing/ss4/vendor/phpunit/phpunit/phpunit:52

FAILURES!
Tests: 1, Assertions: 3, Failures: 1.
```

**Comment by maxime-rainville** [comment]
That's good with me. I'll close this one for now. Once you got travis going and maybe reopen this issue if you're still seeing weird behavior in your unit test.

**Comment by nglasl** [comment]
Will do, cheers.
