### ISSUE TITLE
[bug] Deleting a versioned object leaves the live object in place

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-versioned#156]
Using the nzta/banner module, the following occurs:
- If you have a published banner, and you delete it, it doesn't unpublish, and then you have no way of accessing it, so you just have a permanent banner.

**Comment by kinglozzer** [comment]
Duplicate of https://github.com/silverstripe/silverstripe-versioned/issues/78?

**Comment by dhensby** [comment]
yep
