### ISSUE TITLE
Remove markup from translation files

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-versioned#188]
~~SilverStripe 4.2.1, Versioned 1.2.1:~~

~~If a user attempts to access a staged page URL while logged out, the error message shows un-parsed markup in the message:~~

```
You must log in with your CMS password in order to view the draft or archived content. 
<a href="/sandbox?stage=Live">Click here to go back to the published site.</a>
```

@robbieaverill: the above issue is present in SilverStripe 4.2.1 but fixed in 4.2.2.

---

As far as I know, from looking at this problem over a year ago, the advice was not to use markup in language files. See: https://github.com/silverstripe/silverstripe-framework/issues/6537 - and indeed this text and markup is included in the following file:

`./vendor/silverstripe/versioned/lang/en.yml`

We should remove all HTML from translation files.

**Comment by maxime-rainville** [comment]
I didn't managed to get the unparsed markup. Have you done anything special to your error pages or your error handlers?

I agree, we should try our best to not use HTML in translations.

**Comment by robbieaverill** [comment]
I can reproduce this on 4.2.1, but it's fixed in 4.2.2.

Let's convert this issue into a "remove markup from translation files" issue

**Comment by robbieaverill** [comment]
We'll also have to do this from the 1.0 branch and merge it up to prevent issues with translations changing in earlier release versions.

**Comment by robbieaverill** [comment]
Closing in favour of tracking this here: https://github.com/silverstripe/silverstripe-framework/issues/6537
