### ISSUE TITLE
Write a clean-up task to "declutter" history DB tables

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/silverstripe-versioned#198]
### Description

Currently on larger websites it's possible for history tables to grow to the size of millions of records. It would be nice if there was a task provided (and possibly enabled by default when supported modules are installed) that cleaned up records with some configurable criteria.

Some quick-fire (configuration) ideas:
- Delete all but published records
- Delete all but 1 record per week at a certain age (ie. delete all page records that are 3 months old but leave 1 record per week)

Admittedly I don't have much experience working as or with content editors so I'm not sure what would be reasonable here.

**Comment by robbieaverill** [comment]
I'd suggest maybe that we have a configurable age for versions to be kept, e.g. one month, and any draft records older than that are removed (unless the record is in a modified state - don't delete that). We could also configure it to delete either draft or published or both after that age

**Comment by stevie-mayhew** [comment]
See https://github.com/axllent/silverstripe-version-truncator

**Comment by chillu** [comment]
This is a hard problem ™️ . @ScopeyNZ and @unclecheese both don't think we should support this in core for this reason - it's pretty complex to find out which versions are no longer being relied on without full referential integrity and some pretty gnarly ORM introspection. It's a good idea as long as the limitations are documented, but should live in a module - hence closing here.

**Comment by chillu** [comment]
This popped up again in https://github.com/silverstripe/silverstripe-versioned/pull/335

**Comment by brynwhyman** [comment]
And there's now a new module in development to address this!  https://github.com/brettt89/silverstripe-garbage-collector
