### ISSUE TITLE
[Warning] on count() with PHP >= 7.2 with 3.7.2

### ISSUE THREAD

**Issue by lerni** [silverstripe/silverstripe-versioned#202]
## Affected Version
3.7.2 with PHP >= 7.2

## Description
On dev/build with PHP 7.2 & 7.3 warnings are thrown
`[Warning] count(): Parameter must be an array or an object that implements Countable`

This happens here:
https://github.com/silverstripe/silverstripe-framework/blob/3.7/model/Versioned.php#L450

On classes `Widget`, `BlogArchiveWidget`, `ArchiveWidget`, `BlogCategoriesWidget`, `BlogRecentPostsWidget`, `BlogTagsCloudWidget`, `BlogTagsWidget`, `TagCloudWidget`, `BaseElement`, `ElementChildrenList`, `ElementChildrenList`, and on my own Subblases of BaseElment

It looks like https://secure.php.net/manual/en/migration72.incompatible.php#migration72.incompatible.warn-on-non-countable-types

See also:
https://slackarchive.silverstripe.org/slack-archive/message/245953

**Comment by robbieaverill** [comment]
You could add a cast to array in the config call line, would you like to make a PR?

**Comment by lerni** [comment]
It happened with 3.7. Now you moved this to silverstripe/silverstripe-versioned. Although 3.7.x has now just limited support, I think this should go in 3.7 as well? I'm not sure where or what branch to PR. Would I need to create a separate PR for 3.7 and here targeting 1.3?

here it would mean to replace `$versionableExtensions = $owner->config()->get('versionableExtensions');` with `$versionableExtensions = (array)$owner->config()->get('versionableExtensions');` at two lines:
https://github.com/silverstripe/silverstripe-versioned/blob/1/src/Versioned.php#L805
https://github.com/silverstripe/silverstripe-versioned/blob/1/src/Versioned.php#L1624

for 3.7 same but in lines:
https://github.com/silverstripe/silverstripe-framework/blob/3.7/model/Versioned.php#L450
https://github.com/silverstripe/silverstripe-framework/blob/3.7/model/Versioned.php#L941

**Comment by robbieaverill** [comment]
Hey @lerni 

Yes SilverStripe 3 is in limited support - this is a PHP warning (which can be disabled), but I think it'd be fine to fix it in the 3.7 branch of framework as well as the 1.0 branch of versioned (we'd merge the change up in this module so it is fixed in all versions) if you'd like to make those two pull requests.

If you're happy to make the changes that would be awesome! I'm happy to review them.

**Comment by robbieaverill** [comment]
Thanks for contributing @lerni! I've merged your SS4 pull request by hand, and the 3.7 PR merged.
