### ISSUE TITLE
[Low hanging fruit] Improve Archive tab ordering

### ISSUE THREAD

**Issue by newleeland** [silverstripe/silverstripe-versioned#207]
The order of the tabs within the Archive has somehow changed order 
- The Archive tabs should be ordered in order of likelihood of usage
i.e. 1. Pages > 2. Blocks > 3. Files > 4. Other

- **Pages** tab should be appear on opening Archive, currently **Others** (gridfields) tab is loaded on default

**Comment by emteknetnz** [comment]
Fixed in https://github.com/silverstripe/silverstripe-versioned-admin/pull/165

**Comment by sachajudd** [comment]
@clarkepaul 'Others' or 'Other' is the only question I'd have regarding this as the issue uses both in the example.

**Comment by clarkepaul** [comment]
"Other" would be my choice @sachajudd

**Comment by emteknetnz** [comment]
Cool, have updated PR to say "Other"
