### ISSUE TITLE
GraphQL logic doesn't apply to custom resolvers

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-versioned#211]
I've created a custom resolver for a versioned page type as part of `scaffolding`, in order to create custom filter arguments. See (non-functioning) implementation below.

The problem is that the `OperationResolver->resolve()` implementation calls `$this->extend('updateList')`. When a custom resolver is defined, `OperationScaffolder->createResolverFunction()` will use that *instead* of the built-in one. Which makes sense, but you need to remember to implement the `updateList` hook in your own resolver, as well as applying the correct extension (e.g. `ReadExtension`) to your resolver class. That's very easy to miss.

I'd suggest that we call the original `OperationScaffolder->resolve()` instead, and call an optional custom "inner" resolver to get the results instead. While retaining the permission checks and `updateList` calls. And allow completely overriding the resolver via a separate config key as an advanced use case rather than the default.

Incomplete example illustrating the issue:

```php
<?php

use GraphQL\Type\Definition\ResolveInfo;
use SilverStripe\CMS\Model\SiteTree;
use SilverStripe\Core\Extensible;
use SilverStripe\GraphQL\OperationResolver;
use SilverStripe\ORM\ArrayList;
use SilverStripe\Versioned\GraphQL\Extensions\ReadExtension;

class PageResolver implements OperationResolver
{
    use Extensible;

   // Breaks because it's already defined on Extensible,
   // but could be solved by applying it via YAML
    private static $extensions = [
        ReadExtension::class
    ];

    public function resolve($object, array $args, $context, ResolveInfo $info)
    {
        if (isset($args['RelativeLink'])) {
            $list = new ArrayList([SiteTree::get_by_link($args['RelativeLink'])]);
        } else {
            $list = Page::get();
        }

        if (isset($args['ParentID'])) {
            $list = $list->filter('ParentID', (int)$args['ParentID']);
        }

        $this->extend('updateList', $list, $args, $context, $info);

        return $list;
    }
}
```

/cc @unclecheese @ScopeyNZ

**Comment by maxime-rainville** [comment]
We've completely re-factored GraphQL since this issue was open.
