### ISSUE TITLE
versioned 1.3 incompatible with silverstripe 4.1

### ISSUE THREAD

**Issue by b-rhodes** [silverstripe/silverstripe-versioned#216]
When using versioned with silverstripe-framework 4.1.5, I get the error:
```
PHP Fatal error:  Interface 'SilverStripe\Forms\GridField\GridField_ActionMenuItem' not found in /var/www/summerset.local/vendor/silverstripe/versioned/src/GridFieldArchiveAction.php on line 20
```
And according to the [Silverstripe 4.2 Changelog](https://docs.silverstripe.org/en/4/changelogs/4.2.0/), GridField_ActionMenuItem was only created in silverstripe 4.2.
However the composer.json for versioned just requires `"silverstripe/framework": "^4"`

**Comment by robbieaverill** [comment]
Would you like to make a PR to update the composer dependency to ^4.2?

**Comment by b-rhodes** [comment]
Done, here it is:
https://github.com/silverstripe/silverstripe-versioned/pull/217

**Comment by robbieaverill** [comment]
Thanks - this should prevent people from installing incompatible versions of framework/cms with versioned in future. Cheers @b-rhodes!
