### ISSUE TITLE
Indicate draft/publish state in GridField list and detail view

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-versioned#22]
## Overview

Versioned records can now be managed by a GridField in a default configuration (via `VersionedGridFieldDetailForm`). SS4 encourages devs to version all their records. But there's no indication to authors if records are versioned in the first place, and in which state they're at the moment.

## Acceptance Criteria

 * A GridField has draft/live indicators in the list view
 * The GridField column can be removed like any other column (e.g. if a more detailed status is required)
 * The same applies to ModelAdmin search results

## Notes

 * GridField column space is precious, so we need to find a space saving way to implement this. We could use the orange circle from the files area, and add a text representation on hover/touch?
 * Some GridFields will have added their own status columns already. Duplication is an inevitable side effect of creating better defaults here

## Related

 * [GridField support for versioned records](https://github.com/silverstripe/silverstripe-framework/issues/7032)

## Pull requests 

~https://github.com/silverstripe/silverstripe-versioned/pull/49~
- [ ] https://github.com/silverstripe/silverstripe-framework/pull/7422
- [x] https://github.com/silverstripe/silverstripe-admin/pull/282

**Comment by chillu** [comment]
@clarkepaul This needs UX feedback and design :)

**Comment by clarkepaul** [comment]
Okay added to my todo list

**Comment by chillu** [comment]
@newleeland @clarkepaul This is in beta4, so will be actioned next week - can you please work on this with high priority?

**Comment by newleeland** [comment]
Potential Prototype: https://invis.io/P3DGEM4TC#/252875113_Gridfield_Listing_Holder_Draft

**Comment by clarkepaul** [comment]
@chillu, @jared has just installed the Framework Test Module as that was a better representation of what a normal grid field looks like, so he can work from that and update the designs to reflect.

**Comment by newleeland** [comment]
@chillu this is the updated design: https://invis.io/P3DGEM4TC#/252875113_Gridfield_Listing_Holder_Draft

@phalkunz mentioned that it could be complicated with getting a status tag on the page toolbar to be influenced by gridfield items.

**Comment by chillu** [comment]
Thanks for considering the inline filtering. That's out of scope for this card, but an interesting direction. I think we should generally consider decoupling GridField filtering from the available columns, it looks nice, but is way too restrictive. E.g. you can't cram a date range into a single input field (easily). Discussion for another day.

In terms of combining the "name" with the "status", that's consistent with the recent TreeDropdownField designs at https://github.com/silverstripe/silverstripe-admin/issues/232, so I'm happy with it. The hover effect won't work for touch screens, since the whole row is currently a click target for the first action. Which is particularly important on mobile/touch (large touch targets). Also, I think the status shouldn't be hidden behind a hover. We're already showing it by default in the tree, and the "draft" status is important enough to show in a list (and be reviewed across all records at a glance without moving your mouse over each record).

It's fine if you can't sort by status for the moment, the GridField UX patterns don't allow for that. An improved filtering mechanism should provide a substitute for that at a later date.

Implementation note: `GridFieldCofing_RecordEditor` and other defaults take their columns from `DataObject->summaryFields()`. Those fields are currently text only, and we shouldn't start mixing in HTML tags there. I don't know how to implement this combined name/status field, but it has to be outside of that DataObject method

**Comment by chillu** [comment]
Alright, here's a starter:

```php
<?php

namespace SilverStripe\Forms\GridField;

use SilverStripe\Core\Convert;
use InvalidArgumentException;
use SilverStripe\ORM\DataObject;
use SilverStripe\Forms\GridField\GridFieldDataColumns;

/**
 * @see GridField
 */
class GridFieldVersionedDataColumns extends GridFieldDataColumns implements GridField_ColumnProvider
{
    protected $versionedLabelFields = ['Name', 'Title'];

    protected function formatValue($gridField, $item, $fieldName, $value)
    {
        if (!in_array($fieldName, $this->versionedLabelFields)) {
            return parent::formatValue($gridField, $item, $fieldName, $value);
        }

        if (array_key_exists($fieldName, $this->fieldFormatting)) {
            return parent::formatValue($gridField, $item, $fieldName, $value);   
        }

        $flagContent = '';
        $flags = $item->getStatusFlags();
        foreach ($flags as $class => $data) {
            if (is_string($data)) {
                $data = array('text' => $data);
            }
            $flagContent .= sprintf(
                "<span class=\\\"badge %s\\\"%s>%s</span>",
                'status-' . Convert::raw2xml($class),
                (isset($data['title'])) ? sprintf(' title=\\"%s\\"', Convert::raw2xml($data['title'])) : '',
                Convert::raw2xml($data['text'])
            );
        }

        $spec = '$value ' . $flagContent;
        $format = str_replace('$value', "__VAL__", $spec);
        $format = preg_replace('/\$([A-Za-z0-9-_]+)/', '$item->$1', $format);
        $format = str_replace('__VAL__', '$value', $format);
        eval('$value = "' . $format . '";');

        return $value;
    }

    public function getFieldFormatting()
    {
        
        return $this->fieldFormatting;
    }
}
```

Notes:
 * You can conditionally apply it in `GridFieldConfig_RecordEditor` if the record has the `Versioned` extension. 
 * Needs to be limited to whitelisted status flags (otherwise info overload)
 * Relies on `SiteTree->getStatusFlags()` which needs to move to `Versioned`
 * Needs some dev docs on GridField usage to describe default behaviour

**Comment by clarkepaul** [comment]
@chillu Just to confirm, is this the approach to have all states in their own column? We would probably need to show published states as well as draft/modified and also prepare to show archived states as well (not to build it but to allow for archived tag).

**Comment by chillu** [comment]
@newleeland @clarkepaul The status indication in the detail form looks a bit out of place in terms of typography because the fonts are larger there. Do you agree, and have any ideas on how to improve it? A background would delineate the label more clearly, but also reduce the contrast. Maybe an outline? Damian suggested we could move the label to the actions area next to the buttons. Perfectly happy if you say that this is the best design for the solution, just thought I'd get your take.

**Comment by chillu** [comment]
> Just to confirm, is this the approach to have all states in their own column? We would probably need to show published states as well as draft/modified and also prepare to show archived states as well (not to build it but to allow for archived tag).

It looks like we can get the "name + label" in a single column going. I don't think we should show "published" as a label, since we don't do that in the page tree either. I take Damian's point about this making "non-versioned records" indistinguishable from "versioned and published records". But overall, data models should be moving to an "everything is versioned" mindset, so this is a non-issue for me. The user still gets a clear indication on versioned vs. non-versioned records in the detail form (presence of a "publish" button). I'm fine with showing the archived state, although that notion isn't supported by GridFields out of the box yet (showing archived records means running fairly specialised queries)

**Comment by clarkepaul** [comment]
We will do another round of concepts for the detailed view showing the status. I actually prefer keeping the status in the header (and not by the south buttons) but it's worth exploring alternatives to ensure we get it the right pattern which can be reused everywhere.
A few reasons for dropping the pill where that we had to increase the intensity of the orange so that contrast met WCAG standards and then the pills stood out intensely especially when there were lot on the same page so we would prefer to keep away from the pills unless they use the orange text (as opposed to white text on orange pill).

**Comment by chillu** [comment]
After discussing with the team this morning, I've split out the "edit view" labels into a separate card: https://github.com/silverstripe/silverstripe-versioned/issues/51

**Comment by chillu** [comment]
@clarkepaul Dropping all the pills, aye! 💊

**Comment by tractorcow** [comment]
It doesn't need to be nearly that complex.

https://gist.github.com/tractorcow/7ec56d269af1040b4cbb5bb41233245d
