### ISSUE TITLE
Trying to view an archived page in CMS throws an error

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-versioned#228]
CWP 2.2.1 / Framework 4.3.1 / PHP 7.1

To replicate:
- Use split view in CMS
- Archive a published page

The following shows in the preview pane (you may need to refresh everything)

[Emergency] Uncaught Symfony\Component\Cache\Exception\InvalidArgumentException: Cache key "Archive.2019-04-12 10:41:27.Stage, 39#e39013ea9d08c0f88c32d513f7393493#14d71035552fef7c92e4b5c611232830_4220e9c92724b2606621f448e917914a" contains reserved characters {}()/\@:

**Comment by dnsl48** [comment]
Cannot reproduce on `silverstripe/installer 4.x-dev`

**Comment by emteknetnz** [comment]
Sorry, I've lost context of this issue

**Comment by dnsl48** [comment]
Ok, I'll close this for now.
We can reopen if we get some more details.
