### ISSUE TITLE
ResettableInterface requires symfony/cache >3.4.0

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-versioned#236]
Reported on Slack

See https://github.com/silverstripe/silverstripe-versioned/blob/1.4.1/src/Caching/ProxyCacheAdapter.php#L22

`Symfony\Component\Cache\ResettableInterface` was introduced in `symfony/cache` version `3.4.0`, framework currently only requires `^3.3@dev`.

If someone tries to install on PHP 7.0.0 - 7.0.8, they’ll get `symfony/cache 3.3.x` installed (because of Symfony’s PHP constraints in newer versions) and an error:

> Fatal error: Interface 'Symfony\Component\Cache\ResettableInterface' not found in .../vendor/silverstripe/versioned/src/Caching/ProxyCacheAdapter.php on line 22

**Comment by robbieaverill** [comment]
Fixed in #237
