### ISSUE TITLE
Add warning to "revert to this version" about cascading unpublish

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-versioned#24]
## Overview

Since `Changeset::revert()` isn't implemented (yet), reverting a page to an older version does not affect any owned records. You are reverting the page, not the changeset. This will confuse authors, since it's different from the publication model. Read the [RFC: Neo Versioning](https://github.com/silverstripe/silverstripe-framework/issues/4932) "4.2.2.7. ChangeSet::revert" for details.

## Acceptance Criteria

 * Cleary indicate the impact of a revert in the "Pages" section to content authors

## Excludes

 * Implementing `Changeset::revert()`

![image](https://user-images.githubusercontent.com/111025/27935639-6ed06cd0-6300-11e7-884e-d37c2cf1c673.png)

/cc @clarkepaul

**Comment by pitchandtone** [comment]
Why would it not revert the changeset? If users think of a group of objects as a single unit (i.e. Page with content blocks), then reverting a changeset would be probably expected behaviour.

Are we making a pragmatic choice right now or a what's the best outcome here?

**Comment by chillu** [comment]
It's the pragmatic choice. Unless a page has "exclusive ownership" of an object (a concept that doesn't exist in SIlverStripe), you need to expect that the object can be modified and published through other paths. Given that you can only have one live version of an object, this means that these unrelated publications might have caused newer versions of this object to go live. If you now revert to an older version of the owner (page), you might inadvertently cause newer content to be unpublished in other contexts.

Example: `Page has_many/owns PromoItem`. The newest `PromoItem` is also listed separately on the homepage. 

1. User A edits a page with content "check out our new prmo"
1. User A edits `PromoItem` on this page, adds  "50% off" title
1. User A publishes this pagecontaining `PromoItem`
1. User B views the homepage, and decides the promo should be for "80% off" (edits and publishes this item)
1. User A notices the "prmo" typo and reverts the page, also reverting the `PromoItem` to "50% off"
1. User B is surprised that the promo shows another value on the homepage now

**Comment by pitchandtone** [comment]
That's fair but it gets more convoluted the more objects levels you have: i.e page -> list -> carousel -> carousel items. Digging through all of those would be a pain, whereas reverting a Changeset would make that a breeze.

Pragmatic is OK, since the architecture of the change set is in place, creating a UI to do this seems relatively straight forward in the future.

**Comment by chillu** [comment]
Removing from milestone, we'll just have to see how this pans out in terms of user expectations for now, running out of time.

**Comment by tractorcow** [comment]
Revert does revert owned objects.

```php
    public function onAfterRollback($version)
    {
        // Find record at this version
        $baseClass = DataObject::getSchema()->baseDataClass($this->owner);
        /** @var Versioned|DataObject $recordVersion */
        $recordVersion = static::get_version($baseClass, $this->owner->ID, $version);

        // Note that unlike other publishing actions, rollback is NOT recursive;
        // The owner collects all objects and writes them back using writeToStage();
        foreach ($recordVersion->findOwned() as $object) {
            /** @var Versioned|DataObject $object */
            $object->writeToStage(static::DRAFT);
        }
    }
```

**Comment by tractorcow** [comment]
Cascading unpublish has been removed also. :)

**Comment by chillu** [comment]
> Revert does revert owned objects.

Hmm, OK. It's the choice between two bad options, each of which will be surprising to some users in some contexts. I think the answer is to make the UI quite explicit ("this item has been published again since, are you sure?"). But same statement as before: Let's see how it pans out in practice first.
