### ISSUE TITLE
Versioned support for injecting over it

### ISSUE THREAD

**Issue by adrhumphreys** [silverstripe/silverstripe-versioned#252]
Not sure exactly where this fits but I figured the concern is with Versioned so I'd raise it here.

Currently Versioned gets injected and then most classes just access it statically via `Versioned::`
This means that if you were to inject over Versioned you will not be updating the methods elsewhere that get called.

Currently in the module itself we call it statically a bunch of different times and then there is the greater problem in which a lot of modules are calling it statically. This presents itself as an issue when you run into places where you need to override the functionality for Versioned.

Such examples can be found as https://github.com/tractorcow-farm/silverstripe-fluent/issues/583

It would be good to have support for being able to change the functions in Versioned by injecting over it or some other means

**Comment by emteknetnz** [comment]
I'm not sure how we'd go about approaching this.  Do you have any suggestions for how we could potentially change how this currently works?

**Comment by kinglozzer** [comment]
The only way I can think would be to change the API to something like the config API, e.g. `Versioned::inst()->getVersionNumberByStage()`. That would allow us to introduce extension points to formerly static methods, and would allow overriding the entire class with Injector (though I think extension hooks would be preferred...)

Assuming that would actually work, it might have to be a major version change. Perhaps we could get away with a minor version if we leave the existing static methods in and alias them like

```php
public static function get_versionnumber_by_stage($class, $stage, $id, $cache = true)
{
    return static::inst()->getVersionNumberByStage($class, $stage, $id, $cache)
}
```

**Comment by adrhumphreys** [comment]
Yeah my thoughts were on changing Versioned to be more or less a proxy to a new class which contained the implementations and could be injected over. Then all existing modules that are calling it statically would behave as expected

**Comment by emteknetnz** [comment]
@adrhumphreys `then there is the greater problem in which a lot of modules are calling it statically` - could you provide a couple of references to other modules that do this

**Comment by adrhumphreys** [comment]
Sure thing, here's just a few examples of it occurring in some modules I'm using for my current project:
- [silverstripe-cms](https://github.com/silverstripe/silverstripe-cms/blob/82387cb4443c8b3736cfdd1c15b831fa1e0efa1f/code/Controllers/CMSMain.php#L1244)
- [silverstripe-assets](https://github.com/silverstripe/silverstripe-assets/blob/42f446e972b00b238ad1f78df1d7e71ad49fa29b/src/AssetControlExtension.php#L178)
- [silverstripe-framework](https://github.com/silverstripe/silverstripe-framework/blob/a80fd433e22c05f0719e5761ced06b8d7cdd63c4/src/Security/InheritedPermissions.php#L298)
- [silverstripe-elemental](https://github.com/dnadesign/silverstripe-elemental/blob/5f384e08f1308aa83ac202f8e3f723c28316b6ad/src/Models/BaseElement.php#L268)
- [silverstripe-admin](https://github.com/silverstripe/silverstripe-admin/blob/0faee38d2c905d3d4baef8e9f340f566f6ecef99/code/CMSBatchAction.php#L170)

**Comment by ScopeyNZ** [comment]
Loz's example is probably how it should be tackled - the version "service" is available in the application container. `Versioned::inst()` is shorthand for `Injector::inst()->get(Versioned::class)`. This would allow developers to avoid service discovery by using the other DI options available in SS.

This does cover @adrhumphreys' expectation, where `Versioned` is an instantiated object, we just leave in `@deprecated` static methods that proxy through for backwards compatibility.

**Comment by emteknetnz** [comment]
@ScopeyNZ ok sounds good - seems like this would just be a new minor release then

@adrhumphreys would you be keen to do a PR for this? I'm available on slack/zoom if required

**Comment by adrhumphreys** [comment]
I'm happy to take a stab at it over the next few weeks

**Comment by ScopeyNZ** [comment]
I've left off the `change/` tag, as I'm not convinced yet that we can safely include this change in a minor release.

**Comment by adrhumphreys** [comment]
Have gone through and made the changes in #257 if you want to review it @emteknetnz  🎉
