### ISSUE TITLE
GridField Item Edit Form should be consistent with the Page Edit Form

### ISSUE THREAD

**Issue by mfendeksilverstripe** [silverstripe/silverstripe-versioned#255]
Consistency is needed for good user experience. Some improvements were already covered in [recent changes](https://github.com/silverstripe/silverstripe-versioned/pull/242), however it's still not matching the `Page Edit Form`.

The goal is to make the UI consistent between `GridField Item Edit Form` and `Page Edit Form`

Fixed in https://github.com/silverstripe/silverstripe-versioned/pull/222

**Comment by emteknetnz** [comment]
The linked PR was merged, closing this issue
