### ISSUE TITLE
Extension point in writeToStage() doesn't pass the stage as param

### ISSUE THREAD

**Issue by mfendeksilverstripe** [silverstripe/silverstripe-versioned#277]
# Extension point in writeToStage() doesn't pass the stage as param

* extension point uses undefined variable
* this doesn't throw only because it's passed as a reference
* in current situation this is effectively the same as always passing `null`

## Short term workaround

* following line of code can be used as a short term workaround until this fix comes through
* put following line into your extension code to determine the stage

```
$stage = Versioned::get_stage()
```

## Solution

Fixed in https://github.com/silverstripe/silverstripe-versioned/pull/276

**Comment by robbieaverill** [comment]
Fixed in 1.6 with #276 thanks to @mfendeksilverstripe
