### ISSUE TITLE
Utilise $owns for recursive duplication

### ISSUE THREAD

**Issue by pitchandtone** [silverstripe/silverstripe-versioned#28]
Since $owns handles versioning cascade, and should handle unpublish, we should also be able to imply duplication (similar to publish). The logic should be similar to the recursive publish method.

# Acceptance Criterea:

  - Any duplicated object will include all owned objects (or duplicates as necessary) from the original
  - Developers can customise the list of objects that are duplicated automatically
  - Documentation describes how this works
  - Tests cover any new features
  
# PRs

  - [x] https://github.com/silverstripe/silverstripe-framework/pull/7819
  - [x] https://github.com/silverstripe/silverstripe-versioned/pull/106

**Comment by pitchandtone** [comment]
I have supplied an example of how we've handled this on Elemental here: https://github.com/silverstripe/silverstripe-versioned/issues/25#issuecomment-314701347

**Comment by pitchandtone** [comment]
@sminnee, @chillu, @tractorcow have also made similar comments here: 
https://github.com/silverstripe/silverstripe-versioned/issues/23#issuecomment-314252517
https://github.com/silverstripe/silverstripe-versioned/issues/23#issuecomment-314253516
https://github.com/silverstripe/silverstripe-versioned/issues/23#issuecomment-314257726

**Comment by tractorcow** [comment]
At the moment we have the following method signature for duplicate:

```
public function duplicate($doWrite = true, $manyMany = 'many_many')
```

What we could do is change it to

```
public function duplicate($doWrite = true, $withOwned = true)
```

So that it allows you to duplicate owned objects, rather than trying to infer it from the relationship type.

Note that many_many currently only duplicates the mapping table.

We could use the following behaviour:

 - $withOwned = true, duplicates owned many_many mapping table, duplicate actual object for has_one and has_many.
 - $withOwned = false, duplicate only this object and not related.
 
@pitchandtone would love to hear your feelings. :)

**Comment by pitchandtone** [comment]
@tractorcow wouldn't matching the publish api signature be better? duplicateRecursive and duplicateSingle? and then deprecating duplicate for v5, but calling Recursive if $withOwned = true

**Comment by sminnee** [comment]
+1 for API consistency.

**Comment by chillu** [comment]
The ticket title reads "Utilise $owns for recursive duplication **and deletion**", but the comments only discuss duplication. On https://github.com/silverstripe/silverstripe-versioned/issues/23 the consensus seems to be that we can't infer delete/unpublish from ownership. Should we limit this ticket to duplication?

**Comment by tractorcow** [comment]
Renamed.

**Comment by tractorcow** [comment]
>  @tractorcow wouldn't matching the publish api signature be better? duplicateRecursive and duplicateSingle? and then deprecating duplicate for v5, but calling Recursive if $withOwned = true

This is fine, since duplicate() is dataobject, but duplicateRecursive() / duplicateSingle() can be versioned specific.

This will make it opt-in though.

**Comment by sminnee** [comment]
My view is:

 * Publication & duplication: inferred from owns
 * Deletion & unpublishing: inferred from cascade_deletes

"Owns" kind of means "cascade_creates"

Make sense?

**Comment by tractorcow** [comment]
Yes I think so.

You agree that with owned many_many, we should only need to duplicate the mapping though, correct?

**Comment by chillu** [comment]
Moving this to `impact/high` so it stays on our radar, since it's a co-fund commitment.

**Comment by tractorcow** [comment]
WIP branches:

 - https://github.com/open-sausages/silverstripe-framework/tree/pulls/4/duplicates-is-easy
 - https://github.com/open-sausages/silverstripe-versioned/tree/pulls/1/duplicates-is-easy
 
 I'm going to have a `cascade_duplications` that will let you override `owns` so you have a degree of control.

**Comment by flamerohr** [comment]
API has been merged, recursive duplication is now available
