### ISSUE TITLE
Version timing

### ISSUE THREAD

**Issue by mfendeksilverstripe** [silverstripe/silverstripe-versioned#289]
# Version timing

This is an issue which mostly affects larger projects with lot of nested data models. When calling `publishRecursive()` on a top level object like page we assume that the core part of the operation (writes) finish within the same second. This may not be the case however for large projects - publish operation may take several seconds. This results in inconsistent version timestamps which may break the rollback feature.

## Example

Page version timestamp is `2020-08-03 10:51:01`
Block version timestamp is `2020-08-03 10:51:03`

Reverting or viewing version for  `2020-08-03 10:51:01` timestamp will show page version which is correct but the block version will be outdated.

One way to test this is to add `sleep(2)` to `onBeforeWrite()` for both the page and the block.

## Solution

Make sure all write use `$now = DBDatetime::now()->Rfc2822();` and use the `DBDatetime::set_mock_now()` to set the timestamp to match the page (as this happens first). All nested objects need to inherit the timestamp from the page when running `publishRecursive()`.

Fixed in https://github.com/silverstripe/silverstripe-versioned/pull/292

**Comment by maxime-rainville** [comment]
I'm marking this has impact/high because it could lead to data inconsistencies that can not easily be remedied.

**Comment by maxime-rainville** [comment]
All related PR have been merged
