### ISSUE TITLE
Support symfony/cache 5

### ISSUE THREAD

**Issue by lekoala** [silverstripe/silverstripe-versioned#350]
Is there a specific reason to not support symfony/cache v5 ? It's been out there for a while

The most relevant changes for this version are

- removed all PSR-16 implementations in the Simple namespace
- removed SimpleCacheAdapter
- removed AbstractAdapter::unserialize()
- removed CacheItem::getPreviousTags()

if these are not used or required, it's probably safe to allow v5 in composer.json

**Comment by dhensby** [comment]
see https://github.com/silverstripe/silverstripe-framework/pull/10187 /

**Comment by lekoala** [comment]
closing this, not relevant anymore :)
