### ISSUE TITLE
HistoryViewer doesn't work when pagetype extends SiteTree

### ISSUE THREAD

**Issue by elliot-sawyer** [silverstripe/silverstripe-versioned#363]
Context: https://github.com/silverstripe/silverstripe-versioned/pull/361

According to the docs, [history viewer should be enabled for SiteTree objects and DataObjects automatically](https://docs.silverstripe.org/en/4/developer_guides/model/versioning/#using-the-history-viewer). However, the graphql query utilised by ReadVersions is calling on Pages, and its subclasses, to render the view. This means if you have a pagetype that extends SiteTree directly, the HistoryViewer will not render with the following error returned by the /graphql endpoint

```
message: "Cannot view versions on Page", code: 0, file: "/path/to/ss411/vendor/silverstripe/versioned/src/GraphQL/Resolvers/VersionedResolver.php", … }
message	"Cannot view versions on Page"
code	0
file	"/home/elliotsawyer/Sites/ss411/vendor/silverstripe/versioned/src/GraphQL/Resolvers/VersionedResolver.php"
line	79
```

Working with @unclecheese on Slack, we determined the issue was at DataQuery line 313. For some reason, the query is getting all subclasses of Page, rather than subclasses of SiteTree. :
```
                $classNames = ClassInfo::subclassesFor($this->dataClass);
                $classNamesPlaceholders = DB::placeholders($classNames);
```

If the documentation is correct, I'd expect this to be a bug? Otherwise, should the docs be updated to say "History Viewer should be enabled for Page objects ..."?

Reproduction steps on 4.11

1. `composer create-project silverstripe/installer 4.11.0-beta1`
2. create a pagetype `class HomePage extends SiteTree` with one $db field `$db = ['Test' => 'Varchar(32)'];` and `$table_name = 'HomePage';`
3. dev/build
4. By default, Home is a "Page" type
5. View History tab, observe that it's working
6. Change Page type to "Home Page' in Settings and publish
7. View History tab, observe that it's not working

**Comment by GuySartorelli** [comment]
Pr merged. Closing this issue.
