### ISSUE TITLE
Deprecated VersionedInputType referenced

### ISSUE THREAD

**Issue by frankmullenger** [silverstripe/silverstripe-versioned#395]
In silverstripe/graphql v4 the TypeCreator class is removed so VersionedInputType is deprecated but it's still referenced here: https://github.com/silverstripe/silverstripe-versioned/blob/1/src/GraphQL/Plugins/VersionedRead.php#L51 

The reference throws a bunch of errors when querying the silverstripe/graphql v4 GraphQL service e.g:
"Call to undefined method SSGraphQLSchema_hash\Types::VersionedInputType()".

**Comment by GuySartorelli** [comment]
@frankmullenger Can you please give some more information? ~~I agree this reference shouldn't be in here but I'm just trying to figure out when this code is actually reached.~~
Can you please provide some simple steps to reproduce the errors you experienced?

Edit: I think this reference is valid - see `_graphql/types.yml` where the `VersionedInputType` is declared. Steps to reproduce your specific issue are needed to see what's going on there, but it's almost certainly not related to the deprecated graphql 3 version of `VersionedInputType`. It _might_ be related to https://github.com/silverstripe/silverstripe-graphql/issues/500 but without more information (steps to reproduce, full stack trace, etc) it's impossible to know for sure.

**Comment by GuySartorelli** [comment]
Taking off the complexity and impact labels until we have more information.

**Comment by frankmullenger** [comment]
@GuySartorelli pretty sure I just installed this module and built the default schema then ran a basic query or something like that, I think any query failed and basically it didn't work for me ootb. I'm not familiar with how the GraphQL service runs under the hood here but it seems like this `VersionedInputType` is reliant on the `TypeCreator` class: https://github.com/silverstripe/silverstripe-versioned/blob/1/_legacy/GraphQL/Types/VersionedInputType.php#L14 which does not appear in `silverrstripe/graphql` v4 afaict. Perhaps there's some kind of `AbstractTypeRegistry` which doesn't pick it up because PHP returns before the class is defined effectively.

This deep link might not be working as well as it could:
https://github.com/silverstripe/silverstripe-graphql/compare/3.8.1...4.0.0#diff-e58da0544aeeab9dc55eb116bfa22f7ec63448e7ee15938cdb3a9da26f3c7b99

...but you can have a look for `TypeCreator.php` in that diff and it looks like the file was deleted, so using v4 will mean that VersionedInputType will return early, the TypeCreator class does not exist. Using v4 appears to be valid given the composer constraints: https://github.com/silverstripe/silverstripe-versioned/blob/1/composer.json#L29. Hth.

**Comment by GuySartorelli** [comment]
> pretty sure I just installed this module and built the default schema then ran a basic query or something like that

This is not enough information for me to reproduce the error.

> I just installed this module

do you mean you had a project _without_ versioned, and then you added it? If so, what was in your composer.json dependencies beforehand?

> built the default schema

Do you mean "default schema" in the way graphql means it (i.e. a custom schema)? If so, what was in your custom schema? If not... what did you mean?

> ran a basic query or something like that

As in you were running existing queries in javascript which is set up already in silverstripe/admin or another module? Or were you executing specific queries manually via javascript or via the graphql-devtools module?

I've tried setting up a new installer project and running `dev/graphql/build` to build the schema. I've tried both clicking around the admin focusing on things like history panel and archives and triggering queries manually _which explicitly use the `VersionedInputType` type_ using graphql-devtools. I cannot reproduce this, so can you please provide some clear step-by-step instructions for reproducing it?

>  it seems like this VersionedInputType is reliant on the TypeCreator class: https://github.com/silverstripe/silverstripe-versioned/blob/1/_legacy/GraphQL/Types/VersionedInputType.php#L14 which does not appear in silverrstripe/graphql v4 afaict.

Yes. But _that_ `VersionedInputType` class is only ever loaded if graphql v3 is installed. If you're using graphql v4 it uses the `VersionedInputType` type which is defined in yaml config in `_graphql/types.yml` as I mentioned in my previous comment.

**Comment by frankmullenger** [comment]
Strange, I didn't expect this to be difficult to reproduce to be honest! It was just an error that popped up on a project with a fairly vanilla GraphQL set up. I simply took a stab at what the cause might be and removing the `$query->addArg('versioning', 'VersionedInputType');` fixed it for me and it seemed like there was an error in regards to relying on `TypeCreator.php` here. 

I'll try and find some time to document better steps to reproduce, but it might be a while before I get to that, if you can't reproduce feel free to close :-)
