### ISSUE TITLE
Version 1.13.0 breaks symbiote/silverstripe-advancedworkflow diff functionality

### ISSUE THREAD

**Issue by jules0x** [silverstripe/silverstripe-versioned#405]
Removed deprecated functionality in this version appears to cause the workflow diff functionality to stop working.

https://github.com/symbiote/silverstripe-advancedworkflow/issues/488

## Acceptance criteria
- We've identified which change  in the 1.13 release has caused the regression.
- Workflow Action tab displays the relevant diff.
- Relevant deprecation are still enabled.
- Workflow module behat test are updated to identify this failure in the future.

## PRs
- https://github.com/silverstripe/silverstripe-versioned/pull/406
- https://github.com/symbiote/silverstripe-advancedworkflow/pull/492

**Comment by GuySartorelli** [comment]
What functionality has been removed? I'm not aware of any deprecated functionality which was removed in 1.13.0.

**Comment by maxime-rainville** [comment]
@jules0x This doesn't give us much to go on.

Can you provide a bit more details
- Replication steps
- What's the actual behaviour you are seeing and what the expected behaviour.

**Comment by toknz** [comment]
@maxime-rainville I've added a comment on the issue in
https://github.com/symbiote/silverstripe-advancedworkflow/issues/488

**Comment by Candess** [comment]
@maxime-rainville I faced the same issue after CMS upgraded to 4.13 (Note: Silverstripe/versioned upgraded to 1.13.0 from 1.11.1).
The steps to get the error:-
1. User edited the page content and saved
2. Click on Submit for approval
3. Workflow Actions tab displayed with empty data. The fields should not be empty.
![image](https://github.com/silverstripe/silverstripe-versioned/assets/135276483/537f03ab-e22d-4b09-b456-1790568830fb)

**Comment by maxime-rainville** [comment]
Thanks for the extra info everyone. I managed to replicate the issue and confirm that it doesn't OK with versioned 1.12 installed.

[simplescreenrecorder-2023-06-07_11.41.36.webm](https://github.com/silverstripe/silverstripe-versioned/assets/1168676/3367f558-9666-4275-8abb-f7efb2d20514)

**Comment by maxime-rainville** [comment]
It seems to work fine on CMS 5. I've added some ACs and moved this to our backlog.

**Comment by GuySartorelli** [comment]
This was caused by a missing return statement in https://github.com/silverstripe/silverstripe-versioned/pull/393

**Comment by emteknetnz** [comment]
Linked PR has be merged and released as [1.13.1](https://github.com/silverstripe/silverstripe-versioned/releases/tag/1.13.1)
