### ISSUE TITLE
TODO: DataDifferencerTest::testArrayValues. Investigate issue with using getter.

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-versioned#413]
### Description
Investigate issue with using getter would split up field again. Bug only caused by simulating an array-based value in the first place.
See https://github.com/silverstripe/silverstripe-versioned/blob/f5cd4ed577e32fdf695d1729c78b01d4c21ec094/tests/php/DataDifferencerTest.php#L60-L76

**Comment by GuySartorelli** [comment]
@sabina-talipova I'm not sure what this issue wants us to do.... I don't understand the original todo comment at all lol. Do you understand it?
If not, we should probably just close this one.

**Comment by GuySartorelli** [comment]
Closing as this doesn't seem particularly clear and it's just for a test so we're less likely to spend time on it.
