### ISSUE TITLE
We're calling a method (`having`) that doesn't exist on `DataList`

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-versioned#417]
## Description
Method `having()` doesn't exist in `DataList` class, but we're trying to call it If `Versioned::Versions()` receives `$having` parameter. 

We need to either add that method to `DataList` or apply the `$having` argument via `alterDataQuery()`

See https://github.com/silverstripe/silverstripe-versioned/blob/53594900206c2b1909ce11cfd22286f9c7aaa46f/src/Versioned.php#L2008-L2026

## Acceptance criteria
- The `$having` argument in `Versioned::Versions()` can be called without throwing an exception and can be meaningfully use.

## Note
We are assuming that this can be done relatively easily. But if it turns out to be very difficult, bring it back for re-refinement.

## PR
- https://github.com/silverstripe/silverstripe-versioned/pull/425
- https://github.com/silverstripe/developer-docs/pull/396

**Comment by GuySartorelli** [comment]
Marking as impact/high.
This would be a critical in other circumstances, but the fact that this hasn't caused actual problems until now mitigates its impact somewhat.

**Comment by GuySartorelli** [comment]
PR merged. Reassigning to Steve to add a note to the PR about the deprecated parameter.

**Comment by emteknetnz** [comment]
> Reassigning to Steve to add a note to the PR about the deprecated parameter.

Not sure what I'm supposed to do here?

**Comment by GuySartorelli** [comment]
Changelog, sorry.

**Comment by emteknetnz** [comment]
PR added

**Comment by GuySartorelli** [comment]
PRs merged
