### ISSUE TITLE
Implement API to determine if owned object need to be published

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-versioned#420]
As a developer, I want the capability to determined if they are any outstanding changes on a child object that need to be published.

## Context
@mfendeksilverstripe has already implemented this in a PR #328. This issue is just backfilling.

Note that "owned" in this context is a bit ambiguous, as the PR includes `cascade_duplicates` in its concept of "owned".

## Acceptance criteria
- `Versioned` as a new method that can be called to determined if child object need to be published.
- Owned "children of children" are considered when making a determination of the state of a parent object ... even if the first child is unversioned.
- Any "compromises" that are needed to make this API shippable in a minor release are documented and a follow up card is created to remove them in the next major.

## Notes
- For context, ownership here refers to the `private static $owns` array.

## Edge cases
- Calling the `stagesDifferRecursive` on a DataObject in the `LIVE` stage.
- Do we care about "unversioned" DataObjects that owned other DataObject?
- What happens for "versioned" DataObject that do not use stages?

## Pull requests
- #328

## Parent epic
- #419

**Comment by GuySartorelli** [comment]
PR merged. The API will be available from CMS 5.2
