### ISSUE TITLE
Item that has been added implicitly to ChangeSet, cannot be removed

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-versioned#422]
## Description
Item that has been added implicitly to the ChangeSet as ChangeSetItem,  cannot be remove if explicitly added parent item was removed and ChangeSet has State = 'published'.

### Steps to reproduce
- Create page
- Add an Image to the Page
- Save, but don't publish
- Add the Page to Campaign
- Go to the Campaign Admin
- Open Created Campaign
- You should see your Page in PAGES section and Image in FILES section
- Click on the Page in PAGES section
- Click Remove in "Action Menu"
- Page and appended to the page image were removed form PAGES and FILES sections
- Repeat previous steps before "Click Remove in "Action Menu""
- Instead Click Publish Campaign button
- Click on the Page in PAGES section
- Click Remove in "Action Menu"
- Page was removed form PAGES and Image still exist in FILES sections
- Click on the Image in FILES section
- Click "Action Menu"
- **You should see "Required by {number} item(s), and cannot be removed directly."**

## Related issue
- https://github.com/silverstripe/silverstripe-versioned/issues/415

## PRs
- https://github.com/silverstripe/silverstripe-versioned/pull/423
- https://github.com/silverstripe/silverstripe-campaign-admin/pull/286

**Comment by maxime-rainville** [comment]
I've reviewed #423.

I'm wondering if the correct behaviour shouldn't be to "freeze" a campaign once it has been published. It sounds kind of nonsensical to be able to remove items from Campaign Admin post publication. If the we decide the correct behaviour here is to block people from removing item from published campaign, than the behat PR will need to be updated.

**Comment by maxime-rainville** [comment]
As discussed, we don't think there's a valid usecase for removing item form campaign post publication.

So the second Behat PR is not needed.

I've created this follow up card: https://github.com/silverstripe/silverstripe-campaign-admin/issues/287
