### ISSUE TITLE
Indicate draft/publish state in GridField detail view

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-versioned#51]
# Overview

Authors need context of the current publication status when editing a record. For example, is pressing "publish" just updating an existing record, or publishing a draft for the first time? Split out from https://github.com/silverstripe/silverstripe-versioned/issues/22

# Acceptance Criteria

 * The GridField edit form indicates if the edited objects is in draft mode (meaning the "publish" action will publish this record for the first time)
 * State updates when value is saved
 * Applies to all versioned GridFields by default (incl. ModelAdmin)
 * Applies to pages editing view

# Notes

 * Excludes Files section
 * Label wraps correctly with long titles and breadcrumb chains. 
 * Excludes "last saved" info in button toolbar (unless where it already exists, like in the CMS area)
 * Excludes "propagating" draft state to owners

# Accepted Design

![page_tinymce_states left top](https://user-images.githubusercontent.com/8085295/32310538-e8b96c8c-bff7-11e7-8157-7c09c11db4ec.png)

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-admin/pull/388
- ~https://github.com/silverstripe/silverstripe-framework/pull/7727~
- [x] https://github.com/silverstripe/silverstripe-versioned/pull/86

**Comment by chillu** [comment]
@newleeland Can you please figure out which design we'll implement - breadcrumbs or actions?

**Comment by newleeland** [comment]
![page_tinymce_states action bar](https://user-images.githubusercontent.com/8085295/32310045-7941b4ca-bff4-11e7-85f8-8dd619731f9d.png)
The issue with placing at the bottom is that, tends to last things people see, generally we want to know earlier on, furthermore theres quite a lot things on Toolbar south is quite populated already, especially on mobile view

![page_tinymce_states right top](https://user-images.githubusercontent.com/8085295/32310337-5e6d10ac-bff6-11e7-93bd-82761b81b66a.png)
It could be on the top right however, it is a little out of place in with tabs
![page_tinymce_states right top 2](https://user-images.githubusercontent.com/8085295/32310509-b2160fdc-bff7-11e7-8544-e54a02ff4b56.png)
This is another option, however, it not a consisent pattern we currently have.

**Comment by clarkepaul** [comment]
I'm still in favor of the last approach for the "Draft" status (positioned next to the title). The other examples would also need to consider the "more options" dropdown and other actions. We use the status next to the title consistently in other views eg gridfield, file edit view and it works well.

We do have the idea to show a summary of sorts at the bottom of the page with details of what has changed since an item was last published. This would also be the ideal place for details of who last worked on the item. This idea is still just an idea and hasn't yet been mocked up unfortunately.

**Comment by chillu** [comment]
+1 for the last approach (position next to the title). A more detailed summary (last author, last publisher, last edited date) seems to be like a logically distinct UI element. It's important to see if a page is in draft - it means when you open an item for editing, and it already has a "draft" label, you might go looking for more detail because it might've been edited by somebody else already. For summary information, that's more of a second level of status information which would live at the bottom of the form screen.

**Comment by clarkepaul** [comment]
Suggesting @phalkunz picks up this one and we only need the "Draft/Modified" status to be shown and not date or author at the bottom as that stuff is likely to be wrapped up in a summary of sorts which is a another issue.

**Comment by clarkepaul** [comment]
@phalkunz I think we can use Bootstrap .badge but probably best to create our own version .badge-has-changes or similar.
* use variables $state-draft for text of draft, $state-modified for modified (which are same colour output at the moment).
* use $border-color-light for border
* use $white for bg
* use $btn-block-spacing-y for spacing between title and badge if it equates to something around 6-8px (I would think its 7px?)

Can you also: 
* update $state-draft to the colour #CF3F00
* update $state-draft-bg to #FFF7F0 (don't need to use this for badge but its used for alerts)

**Comment by tractorcow** [comment]
Checking this now.
