### ISSUE TITLE
UploadField with many_many on Image causes too many queries

### ISSUE THREAD

**Issue by DorsetDigital** [silverstripe/silverstripe-versioned#53]
On a fresh install of Silverstripe 4 Beta 3:

Create a simple page class, extending Page with a many_many relationship to the Image class:

```
namespace DorsetDigital\SS4\VersionTest;

use SilverStripe\AssetAdmin\Forms\UploadField;
use SilverStripe\Assets\Image;

class ManyManyPage extends \Page
{

 private static $many_many = [
     'ManyManyPhotos' => Image::class
 ];
 private static $owns = ['ManyManyPhotos'];

 public function getCMSFields()
 {
  $folderName = 'TestPhotos';
  $galleryUploads = new UploadField('ManyManyPhotos');
  $galleryUploads->setFolderName($folderName);
  $galleryUploads->setAllowedFileCategories('image/supported');

  $fields = parent::getCMSFields();
  $fields->addFieldToTab('Root.Images', $galleryUploads);
  return $fields;
 }
}
```

As you add images to the page, the number of SQL queries rises dramatically (hundreds of queries, possibly even thousands), getting to the point where the web server times out during the save process and the page remains unpublished.   A snippet of the query log is attached.

[query_log_snippet.txt](https://github.com/silverstripe/silverstripe-versioned/files/1362478/query_log_snippet.txt)

# PRs

- [x] https://github.com/silverstripe/silverstripe-versioned/pull/59
- [x] https://github.com/silverstripe/silverstripe-framework/pull/7489

**Comment by DorsetDigital** [comment]
I'm not sure if it's helpful, but as part of the testing, I tried the same with a has_one relationship.   Attached is a log dump of the queries involved in adding an image to the has_one on a different page.
[ho_query.log](https://github.com/silverstripe/silverstripe-versioned/files/1362541/ho_query.log)

**Comment by chillu** [comment]
How are you adding images to the page? Are you looping over them in templates? Or is this just rendering the UploadField in the CMS? Having 15 duplicates of the same query is indeed very concerning. It doesn't look like that's a permission check issue either (discussed in https://github.com/silverstripe/silverstripe-framework/issues/7442)

**Comment by DorsetDigital** [comment]
The images are just being dragged-n-dropped onto the uploadField in CMS.     There are no templates in this test site, this is purely CMS behaviour.   A lot of queries fire as the files are uploading, but these don't seem to cause any major issues in terms of the responsiveness of the UI.   The big issue is when the save / publish button is clicked.

**Comment by tractorcow** [comment]
I also suspect AssetControlExtension may be making file save / publish a lot slower.

**Comment by flamerohr** [comment]
I wasn't able to get very far with optimising this, branch for changes are:
`pulls/4.0/many_many_queries_for_images`
on
https://github.com/open-sausages/silverstripe-framework/tree/pulls/4.0/many_many_queries_for_images
https://github.com/open-sausages/silverstripe-versioned/tree/pulls/4.0/many_many_queries_for_images

**Comment by tractorcow** [comment]
I've drafted up an RFC for optimising asset writes by shifting certain operations into a promise.

https://github.com/silverstripe/silverstripe-assets/issues/88

**Comment by tractorcow** [comment]
As far as 4.0.0 is concerned, I've optimised this as much as the API allows me to go.

For 4.1.0 I'd like to look at https://github.com/silverstripe/silverstripe-assets/issues/88 to further optimise and reduce queries / filesystem operations on file writing.
