### ISSUE TITLE
[safari bug] - folders indicates they can be dragged into themselves

### ISSUE THREAD

**Issue by newleeland** [silverstripe/silverstripe-versioned#57]
![screen_shot_2017-10-10_at_11_25_34_am](https://user-images.githubusercontent.com/8085295/31361090-022c5316-adae-11e7-9510-0e2076aa6ed8.png)

when a file and folder is selected and dragged on top of the selected folder, the folder plays droppable animation suggesting to the user it can be dragged into itself.

**Comment by flamerohr** [comment]
Reduced impact, as there is a warning which pops up once you release anyway
