### ISSUE TITLE
RFC Conditional extensible publish

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-versioned#61]
# Overview

In order to prevent unnecessary DB writes this RFC proposes that Versioned::publishSingle() internally checks for changes prior to writing.

This could be done with, for example, Versioned::isModifiedOnDraft(), prior to invoking the body of this method.

# Acceptance criteria

 - Calling publishSingle() multiple times (in sequence) on one record will invoke at most one set of database writes.
 - Records which are previously published and have publishSingle() invoked on it will never write to the database.
 - Extensions can modify the behaviour of this conditional, allowing either a write to be enforced (if it would otherwise detect no change) or vetod.
 - No additional queries other than that already queried and/or cached are used

# Notes
 
 - ChangeSetItem::getChangeType() already has an extension point for modifying the "change type" flag for each item, and already responds to extensions. Ideally the versioned-internal behaviour would be consistent with this.

**Comment by sminnee** [comment]
An alternative approach to this would be to recommend that where the cost of unnecessary `publishSingle()` calls are high, that people create a ChangeSet and then publish that ChangeSet.

This would have a few benefits:

 * We don't need to alter the existing API
 * If people really want to re-publish, they have the option of calling publishSingle()
 * It would get people in the habit of creating ChangeSets for batch operations such as content imports, which may provide opportunities for better UX in the future (e.g. the source of a change could be linked back to the import operation in the UI)

The downside is that batch operations might become a little more verbose to code.

**Comment by tractorcow** [comment]
Ah yes, it does feel like this is in fact an edge case, since publishRecursive() already does the correct amount of checking for us.

Perhaps this should lower the priority of this issue, or rather look at where we invoke publishSingle() outside of changesets?

We could even address this with documentation, rather than direct code. E.g.

```
/**
 * Note: This is intended to be used by ChangeSetItem. If calling externally, please use publishRecursive() instead
 *
 */
```

**Comment by tractorcow** [comment]
Outside of ChangeSetItem, `Versioned::publishSingle()` is only called in tests, so maybe the priority is super low after all. :)

**Comment by sminnee** [comment]
If we decided "don't use publishSingle directly" is our recommendation, then I think the effort should go into documenting the alternatives.

**Comment by sminnee** [comment]
It would be worth considering whether a helper in ChangeSet that makes it easier to populate a changeset would be worthwhile, e.g.:

```php
ChangeSet::populate(function () {
  foreach(Member::get() as $member) {
    $st = new SiteTree;
    $st->ParentID = $profilePageSectionID;
    $st->Title = "$member->Firstname $member->Surname";
    $st->write();
  }
})->publish();
```

ChangeSet::populate() would:

 * Create a new changeset object, write it
 * Set a global switch for all relevant database updates to be added to that changeset (maybe a dataquery param, similar to current stage / current locale?)
 * Call the callback
 * Reset that global switch

If you didn't have that, you'd do this. In this case it's not much different but if there were lots of object-creations it could become more error-prone:

```php
$cs = new ChangeSet;
$cs->write();
foreach(Member::get() as $member) {
  $st = new SiteTree;
  $st->ParentID = $profilePageSectionID;
  $st->Title = "$member->Firstname $member->Surname";
  $st->write();
  $cs->addObject($st);
}
$cs->publish();
```

**Comment by chillu** [comment]
@tractorcow Can you please describe the original driver for this? Was there a place where we called publish repeatedly, where we couldn't logically remove that duplication in the actual usage path?

**Comment by tractorcow** [comment]
The issue was in File recursive publishing, which would call `$this->Parent()->publish()` on write. Instead of fixing #61 we just removed the call entirely.

**Comment by tractorcow** [comment]
With this in mind, should we just close this issue @chillu unless we find it's necessary again?

**Comment by tractorcow** [comment]
more context; The code we removed was the only non-changeset usage, if that minimises the risk surface area. :)
