### ISSUE TITLE
GridField extensions for versioned DataObjects in ModelAdmin should be opt-out, not opt-in

### ISSUE THREAD

**Issue by colintucker** [silverstripe/silverstripe-versioned#64]
After a healthy discussion over on Slack with @tractorcow and others, there is some confusion and frustration in the community about why the automatic detection of `Versioned` objects in `ModelAdmin` was removed, and made opt-in with the `$versioned_gridfield_extensions` private static.

This seems counter-intuitive to me.  The previous behavior in SS4 was that versioned data objects would be automatically detected and the appropriate CMS actions added to the `ModelAdmin` for said object.  It's a case of just adding the `Versioned` extension to your model, and boom, you're off and racing.

Having to tell developers "oh by the way, you'll also need to opt-in to having the admin handle your versioning" just seems unnecessary.  The bar to entry in SS4 has already increased, and it's clear that the versioning of assets in SS4 has created some confusion among devs.  Changes like this only make it more confusing, in my humble opinion.  I believe it should actually be the opposite, that is, opt-out, instead of opt-in.  Thoughts?

## Pull request
 - [x] https://github.com/silverstripe/silverstripe-versioned/pull/80

**Comment by tractorcow** [comment]
Note the issue discussed here is https://github.com/silverstripe/silverstripe-versioned/issues/21

My suggestion is that we should probably turn this on by default for ModelAdmin by default, since it's the "top level" section, similar to how cms pages section has save / publish at the top level.

**Comment by adrexia** [comment]
The acceptance criteria of #21 says `Records managed in ModelAdmin get VersionedGridFieldDetailForm by default (not edited in the context of an ownership record)`. With that change this would feel less like a bug.

**Comment by tractorcow** [comment]
Ah that's right, so we can make this a bug after all. :) Thanks for spotting that @adrexia
