### ISSUE TITLE
Inconsistency: Publishing files linked in HTMLEditorField 

### ISSUE THREAD

**Issue by bummzack** [silverstripe/silverstripe-versioned#75]
# Acceptance Criteria

 * Files and images are tracked in each `HTMLText` field regardless of record type
 * As a dev upgrading from SS3 or starting over with SS4, I don't have to do do anything special to get this behaviour
 * As a dev ugprading to SS4 (from 3.x or <=4.1), I retain the existing tracking data
 * As a dev, I can opt into running a migration task that backfills this data for non-page records
 * As an author, this change does not impact my saving and publishing behaviour (performance)
 * As an author, I can see new link tracking info in the "file usage" tab on AssetAdmin

# Notes

 * Excludes "HasBrokenLink" / "HasBrokenFile" on global dataobjects (retained only for SiteTree)
 * Both the dev/build and migration tasks work on large databases (50k records)
 * Excludes versioned tracking
 * Not doing ORM refactor for polymorphic many_many (using existing API)
 * Track under ORB-175

# Original Description

Issue found with silverstripe-versioned `1.0.1`

When a file is inserted/linked inside the `HTMLEditorField` it's not getting published if the parent is a `DataObject`.

Consider these three cases:

 -  `SiteTree`: upon publish, files linked in `HTMLEditorField` get published as well
 - `DataObject` (non-versioned): upon saving, files linked in `HTMLEditorField` are still unpublished
 - `DataObject` (versioned): upon publishing, files linked in `HTMLEditorField` are still unpublished

I guess not publishing files in unversioned `DataObjects` is reasonable, still, it would be nice to have a config flag for this (or a way to publish the file from the "insert file" dialogue).

Publishing a file that is in an editor-field of a _versioned_ `DataObject` should behave the same as `SiteTree` though.

# PRs:

 - [x] https://github.com/silverstripe/silverstripe-framework/pull/7988
 - [x] https://github.com/silverstripe/silverstripe-framework/pull/7928
 - [x] https://github.com/silverstripe/silverstripe-cms/pull/2123
 - [x] https://github.com/silverstripe/silverstripe-assets/pull/122
 - [x] https://github.com/silverstripe/silverstripe-versioned/pull/137
 - [x] https://github.com/silverstripe/silverstripe-framework/pull/7960
 - [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/754

Dependent issue:

- [x] https://github.com/silverstripe/silverstripe-framework/issues/7962
  - [x] https://github.com/silverstripe/silverstripe-framework/pull/7963
  - [x] https://github.com/silverstripe/silverstripe-versioned/pull/138

**Comment by dhensby** [comment]
> I guess not publishing files in unversioned DataObjects is reasonable, still, it would be nice to have a config flag for this (or a way to publish the file from the "insert file" dialogue).

I'm not sure it is. A Live resource shouldn't be referencing content that can't be displayed

**Comment by bummzack** [comment]
> I'm not sure it is. A Live resource shouldn't be referencing content that can't be displayed

What if you have the same content linked in an unversioned and versioned context? Should the unversioned context have precedence over the versioned one?
I think you're right that an unversioned object is a Live resource and would be best treated as always published, but from an UX perspective, it's quite problematic. The "Save" button doesn't indicate any publishing at all… and if users learn that their content gets published when using the "Publish" button, doing the same when "Saving" might be confusing.

**Comment by dhensby** [comment]
> What if you have the same content linked in an unversioned and versioned context? Should the unversioned context have precedence over the versioned one?

If it leaves the unversioned content broken, then sure? the versioned content will still work.

In my view the author has given implicit permission to publish the asset by including it in a live record

**Comment by guyvanbael** [comment]
Just expressing my opinion here. My experience so far is that content authors are realy confused about having to publish images. They just want to add/edit content and the confusing part is that - as long as they are logged into the cms - they can see the result of their changes. But reality is that when they leave the cms, some of the content is not visible for their site-visitors and unless they check again, in most cases, they don't even know that some of their content isn't published. From an advanced user/developers point of view, i can understand this policy, but for the avarage user, it just makes things more complicated and in my opinion, the incredible usability of the cms has always been its simplicity. For dataobjects and has_one images, the developer can fix this whit the static variable $owns, but as far as the htmleditor goes, i think this should be published by default.

**Comment by dhensby** [comment]
I agree - we should be aiming for what "makes sense" for a content author and developers have to work around that.

If a content author adds an image to an un-versioned object and saves it, that image should also be view-able with the saved content without extra steps for the author

**Comment by flamerohr** [comment]
For Pages there is the backlink tracker, which would help alleviate the issue for that case...

But yeah, I agree with that aim

**Comment by tractorcow** [comment]
Just to check in, I understood that files embedded in html areas should be tracked via back link tracker. What is necessary here is an equivalent for non-page parent records.

I.e. generalise class SiteTreeLinkTracking so that it works for non-Sitetree objects.

This may need to be re-classified as an enhancement if we are adding new functionality.

**Comment by chillu** [comment]
Oh my, yes that's a high priority issue, I can see how that'll be very confusing to authors. Moved it to the top of the backlog.

The mention of `SiteTreeLinkTracking` confused me at first. This is just about publishing `File` and `Image` references in `HTMLText` fields. Which could use the same parser as `SiteTreeLinkTracking`, and use the `$owns = ['ImageTracking']` relationship to publish any detected images. It would be great to have those relations tracked in non-SiteTree objects, but I don't think that's necessary for a baseline solution. We could use the `SiteTreeLinkTracking_Parser` separately? Anyway, whatever solution we come up with, it should not require every dev to remember to add an extension to their `DataObject` subclass when adding an `HTMLText` field - that's one more trap that most devs will fall into when starting out with SilverStripe, and a really tough one to debug.

**Comment by tractorcow** [comment]
I had a bit of chat with @flamerohr and I think we could solve this at a global level with minimal overhead:

# Status quo

At the moment there are two extensions, one added to SiteTree, the other to File. This extension tracks a single field, and creates a SiteTree_LinkTracking table to map these.

# Suggestion

Instead, create a new model with a single extension `DataObjectFileTracking` and apply this to the base dataobject class. This will add a single `many_many` through to a `LinkTracking` dataobject, which has two has_ones:
  - Parent: Polymorphic relation to DataObject (ParentClass / ParentID fields)
  - File: File relation to the file being tracked.
  
Although it may be possible to version this, I suggest that we do not do this up front, as the link tracking is mostly only useful in CMS (draft mode). However, in the future this would enable us to version the `through` table as well.

Instead of a belongs_many_many on File, however, we would ONLY have a has_many pointing back to the mapping table. This is because many_many cannot be polymorphic (yet). We can, however, have a has_many to a dataobject which has a has_one to a polymorphic item. :D

The dataobject parent extension would have `owns` on the mapping table, which would in turn `owns` File.

**Comment by chillu** [comment]
Awesome, elegant solution! I assume `LinkTrackingExtension` would be applied by default to `DataObject` if you've got the `assets` module installed? We'd also need a data migration task, and provide some backwards compat on the existing relation getters, but that should be doable.

**Comment by tractorcow** [comment]
Assigning this to myself before someone grabs it. :)

**Comment by tractorcow** [comment]
So apparently the old many_many used to track the field name also. I don't think this is really important, since we can merge all fields before generating the many_many listing.

@chillu just letting you know that we may not internally store that anymore. Strictly this is a semver violation but probably has no significant impact. Keeping this field means worse code that adds no value.

**Comment by chillu** [comment]
I think that's acceptable, yes. Just point it out in the upgrade guide

**Comment by tractorcow** [comment]
Minimal changes to manymanythroughlist to get this working at https://github.com/silverstripe/silverstripe-framework/pull/7928

**Comment by tractorcow** [comment]
I got the above working for sitetree links.

https://github.com/silverstripe/silverstripe-cms/pull/2123

Tomorrow I do the same for assets.

**Comment by guyvanbael** [comment]
To make sure every image/file gets published i'm using this fileextenstion now. Does your solution meansd that this won't be necessary anymore from 4.1.1 on?

`use SilverStripe\ORM\DataExtension;

class FileExtension extends DataExtension 
{
    public function onAfterWrite()
    {
        parent::onAfterWrite();
        $this->owner->publishRecursive();
    }
}`

**Comment by tractorcow** [comment]
Yes it will mean that :D

**Comment by torindul** [comment]
Was this ever merged into a SS branch? I'm on 4.1.1 and still appear to see issues with this.

**Comment by flamerohr** [comment]
@torindul the fix for this is merged in to the `4.2` release :)
as commented here as well https://github.com/dnadesign/silverstripe-elemental/issues/210#issuecomment-380626472

**Comment by torindul** [comment]
Perfect. When is 4.2 pencilled for release or is it already and I’m being silly?

**Comment by flamerohr** [comment]
`4.2.0-beta1` just released last week, you could also switch to the `4.2` branch if you're keen to try it
It is a `beta` release, so it's still going through a bit of stability checks
