### ISSUE TITLE
Preview does not respect version of record

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-versioned#92]
This is likely a regression from 3.x. If you preview older page content through the "History" panel, it will always set the URL to `<my-page>/?stage=Stage&CMSPreview=1`, and not include an `archiveDate` parameter or point to the specific record version.

**Comment by robbieaverill** [comment]
Might be worth adding a simple behat test for this

**Comment by tractorcow** [comment]
@chillu it only does this if you preview the version that is === draft version. When previewing older versions it uses archiveDate. Not a bug. :)

**Comment by chillu** [comment]
Doh, sorry for wasting your time on this!
