### ISSUE TITLE
Archive mode should include all versioned records

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-versioned#93]
# Overview

Content authors, owners and auditors want to have certainty that changes to the website are recorded correctly, both for auditing purposes and to restore content to an earlier state. The main way this detail is exposed to users is through the "History" view. Users can select an older version and preview a page at this past state. In SilverStripe 4, we're relying on versioned objects and nested relationships more strongly. These should be consistently included in previews of older versions.

# Acceptance Criteria

 * The archive mode includes nested relationships for the website preview panel
 * The archive mode includes nested relationships for readonly CMS form showing the record (incl. related records shown there)
 * Works with nested versioned relationships (e.g. Page has_many GalleryContentBlock has_many GalleryItem has_one Image)
 * Works regardless of ownership on relationship
 * Works with has_one and belongs_to
 * Works with has_many
 * Works with [many_many through](https://docs.silverstripe.org/en/4/developer_guides/model/relations/#many-many-through-relationship-joined-on-a-separate-dataobject) where all three models are versioned
 * Respects the given stage of the versioned record. I.e. viewing an unpublished record will show the stage version of all nested records, but viewing the published record will show the live website at that point in time.
 * Respects records which have been unpublished (but not deleted), either by showing them on draft, or not showing them on live.
 * Respects sort order on has_many and many_many
 * Hides records which have been created after the previewed version
 * Hides records which have been created before the previewed version, but have been associated through a versioned relationship after the previewed version
 * Shows records which have been deleted after the previewed version
 * Does not rely on specific version associations in versioned relationships (uses archive date)

# Scenarios

## Delete owned with republishing owner

 * Create Page1
 * Publish Page1v1
 * Create GalleryBlock1, add to Page1
 * Publish Page1v2 (publishes GalleryBlock1v1)
 * Delete GalleryBlock1 ("archive")
 * Publish Page1v3

Expected: Viewing Page1v3 should not show GalleryBlock1

## Delete owned without republishing owner

 * Create Page1
 * Publish Page1v1
 * Create GalleryBlock1, add to Page1
 * Publish Page1v2 (publishes GalleryBlock1v1)
 * Delete GalleryBlock1 ("archive")

Expected: Viewing Page1v2 should show GalleryBlock1

## Delete nested owned without republishing owner

 * Create Page1
 * Publish Page1v1
 * Create GalleryBlock1, add to Page1
 * Create GalleryBlockItem1, add to GalleryBlock1
 * Create GalleryBlockItem2, add to GalleryBlock1
 * Publish Page1v2 (publishes GalleryBlock1v1, GalleryBlockItem1v1, GalleryBlockItem2v1)
 * Delete GalleryBlockItem2v1

Expected: Viewing Page1v2 should show GalleryBlock1, GalleryBlockItem1 and GalleryBlockItem2

## Add association after record has already been published

With CompanyPage many_many OfficeLocation through CompanyOfficeLocations

 * Create OfficeLocation1 (don't add to CompanyPage)
 * Publish OfficeLocation1v1
 * Create CompanyPage1
 * Publish CompanyPage1v1
 * Add OfficeLocation1 to CompanyPage1
 * Publish CompanyPage1v2

Expected: Viewing CompanyPage1v1 should not show OfficeLocation1. Viewing CompanyPage1v2 should show OfficeLocation1.

# Technical implementation details

 * Deleted records will now create a _Versioned row with WasDeleted flag set to true.
 * _Versioned rows will now record a flag for all stages this row affects. This could either by adding a Stages enum (Draft/Live/Both), or by adding a WasDraft to complement WasPublished.
 * Any changes that modify live will now create a new version, even if copying from the draft. This is because historic _Versioned rows cannot "change" the stage they originally aplied to. This may require us to ignore the $createNewVersion flag on copyVersionToStage, and force it to true.
 * Ensure that unpublish actions creates a WasDeleted = true, stage=Live row
 * Ensure that archive actions creates a WasDeleted = true, stage=Both row
 * Ensure that delete (draft only) creates a WasDeleted = true, stage=Draft row
 * Need to add a Stage query parameter to archiveDate since we now care about the stage and not only the date. This stage will filter by the Stage column on _Versioned

# Notes

 * Ingo has tested the basics of this, it's expected that this issue is mostly validation of existing functionality
 * Preview is currently [broken](https://github.com/silverstripe/silverstripe-versioned/issues/92), it only shows the draft version, not the archive mode
 * This is unrelated to changesets. Previewing a website at a time when a changeset was published would simply involve setting the archiveDate to the changeset's publication date.
 * Relies on "soft delete" defaults of Versioned records (no way for user to fully delete a record)
 * We don't [document](https://docs.silverstripe.org/en/4/developer_guides/model/versioning/) direct `many_many` versioning (without through). I'm unsure if this is actually implemented as an API, it was discussed in earlier drafts of the ChangeSet API proposal.
 * In most cases, content authors will be encouraged (or restricted) to publishing content through a cascading publish from the top level (e.g. publishing a page publishes all its blocks). If content authors are allowed to publish nested content individually, there won't be a way to preview this "intermediate" publication state separately from the previous page version. It would require manually setting the correct archive date, or building this feature into the [general purpose history viewer](https://github.com/silverstripe/silverstripe-versioned/issues/37). Once we have [activity feeds](https://github.com/silverstripe/silverstripe-versioned/issues/68), you should be able to preview every nested change linearly over time, regardless on where it happened in the nesting levels.

## Pull Requests
- [x] https://github.com/silverstripe/silverstripe-versioned/pull/131
- [x] https://github.com/silverstripe/silverstripe-cms/pull/2122

**Comment by tractorcow** [comment]
This will probably require us to implement a proper readonly gridfield.

Related story https://github.com/silverstripe/silverstripe-framework/issues/3357

**Comment by chillu** [comment]
Doing a spike first: https://github.com/silverstripe/silverstripe-versioned/issues/110

**Comment by chillu** [comment]
>  * Respects stage selection: Shows draft or live stage in archive date

I've removed this AC, since there's no clear use case for viewing what's been on draft at some point in the past. This might just be a quirk in the current UI, which shows draft/live toggles in the preview window even when the site is in "archive mode"

**Comment by NightJar** [comment]
The API for this will be necessarily employed for https://github.com/dnadesign/silverstripe-elemental/issues/92

**Comment by chillu** [comment]
@NightJar This won't fix your versionfeed integration issue, but https://github.com/silverstripe/silverstripe-versioned/issues/68 should

**Comment by chillu** [comment]
>  * The archive mode includes nested relationships for diff views between two versions of a record

Removed this AC, it's captured in https://github.com/silverstripe/silverstripe-versioned/issues/97

**Comment by tractorcow** [comment]
Candidate A/C changes and extra notes at https://github.com/silverstripe/silverstripe-versioned/issues/110#issuecomment-365792825

**Comment by chillu** [comment]
Added ACs based on Damian's suggestions:

>  works with belongs_to
> Respects the given stage of the versioned record. I.e. viewing an unpublished record will show the stage version of all nested records, but viewing the published record will show the live website at that point in time.
> Respects records which have been unpublished (but not deleted), either by showing them on draft, or not showing them on live.

**Comment by clarkepaul** [comment]
@chillu Am I right in thinking this issue is not for the presentation layer anymore and that would be covered by this issue https://github.com/silverstripe/silverstripe-framework/issues/6202 if we decided to go ahead with the global archive/trash.

**Comment by chillu** [comment]
Yes, this is a data model issue - it's making the preview consistent with what the CMS view would already show in "archive mode".
