### ISSUE TITLE
History Viewer: Compare two versions

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-versioned#96]
# Acceptance Criteria

 * I can compare two revisions and see visual differences on each of their CMS fields
 * I can enter the "compare mode" through a visual trigger
 * I get clear indications that this capability exists when I've selected only one version
 * I can cancel out of this view and get back to selecting another version to compare
 * I can unselect one of the two versions and select another one
 * I can share this view by URL to other CMS authors
 * I shouldn't be allowed to select an already selected version to compare with itself

# Notes

 * Track design time against ORB-175 Pattern Library
 * Designs at https://invis.io/FJEHOLLEN#/263513634_Pages_History_Tab
 * Should not use a React popover, since that would complicate the implementation. Use a checkbox or some other simpler toggle instead. We'll move the feature into a popover once we implement [toggle unpublished versions](https://app.zenhub.com/workspace/o/silverstripe/silverstripe-versioned/issues/105)
 * Bonus points: Make it work across pagination pages
 * We might need to activate the compare mode programmatically here to avoid creating a dependency on a popover field
 * Excludes visual diffs for relationships (e.g. GridField)

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-admin/pull/576
- [x] https://github.com/silverstripe/silverstripe-admin/pull/557
- [x] https://github.com/dnadesign/silverstripe-elemental/pull/310
- [x] https://github.com/silverstripe/silverstripe-admin/pull/592
- [x] https://github.com/silverstripe/silverstripe-versioned-admin/pull/33
- [x] dnadesign/silverstripe-elemental#303
- [x] silverstripe/silverstripe-cms#2221

**Comment by chillu** [comment]
@clarkepaul We'd need a (simple) design for the MVP solution here, as discussed before: Toggle compare mode through a checkbox or something, instead of building a popover.

**Comment by clarkepaul** [comment]
Cool, will arrange

**Comment by clarkepaul** [comment]
Here's the design for the simplified toggle to enter/exit compare mode. Draft items will be shown all the time in the mix of published items initially so we wont require the dropdown.
<img width="582" alt="pasted_image_2_02_18__2_29_pm" src="https://user-images.githubusercontent.com/555033/35712152-87681eee-0825-11e8-9b33-c9b8680e239a.png">

**Comment by robbieaverill** [comment]
>I can share this view by URL to other CMS authors

Does this include the compare mode and selections? I.e. a form of serialized React state?

**Comment by chillu** [comment]
Definitely includes the view comparing two versions (that's the most useful bit), as well as when you've selected a single version (which should display that version as a readonly form). But it doesn't need to include your selection of enabling compare mode, or if you've opted to show unpublished versions. It's technically possible to include those, but low value IMHO.

**Comment by raissanorth** [comment]
Just looking into comparison libraries that might be suitable for this.:

https://github.com/davidmason/react-stylable-diff might work. Unfortunately https://github.com/cezary/react-diff/blob/master/dist/react-diff.js is not maintained any longer it appears. 

Then there is https://www.npmjs.com/package/diff 

Any thoughts or suggestions?

**Comment by robbieaverill** [comment]
https://github.com/davidmason/react-stylable-diff is a fork of https://github.com/cezary/react-diff/pulls - looks like this was done because the original was abandoned, but the fork doesn't look particularly active either...

**Comment by tractorcow** [comment]
ok, so this is what I think we could do for PHP server side;

```php
class DiffFormTransformation extends FormTransformation
{
}
```

```php
class FormField 
{
	public function performDiffFormTransformation()
	{
		// Note: sub-classes such as UploadField can subclass / extend this method 
		// if they don't want to use DiffViewField
		return DiffViewField::create($this);
	}
}
```

```php
class DiffViewField extends FormField 
{
	/**
	 * Field which is used to contain the diff.
	 * Value of $field->Value() is the "to" value.
	 * Value of $this->Value() is the "from" value.
	 */
	protected $field;
	
	public function __construct(FormField $field) 
	{
		$this->field = $field;
		$this->setFailover($field);
	}
	
	// just about every method just passes through to $field as failover
	
	public function getSchemaComponent() 
	{
		return $this->field->getSchemaComponent();
	}
	
	public function getSchemaState()
	{
		$fromValue = $this->dataValue();
		$toValue = $this->field->dataValue();
		$state = $this->field->getSchemaState();
		$state['data']['diff'] = [
			'from' => $fromValue,
			'to' => $toValue,
		];
		return $state;
	}
}
```

and when you build the form with the value you can do something like this.

```
$form = $formbuilder->getForm();
$form->loadDataFrom($toRecord);
$diffForm = $form->transform(new DiffFormTransformation());
$diffForm->loadDataFrom($fromRecord);
```

**Comment by robbieaverill** [comment]
Related: https://github.com/silverstripe/silverstripe-framework/issues/8053

**Comment by robbieaverill** [comment]
PR is at https://github.com/silverstripe/silverstripe-versioned-admin/pull/33. It's been reviewed internally (but also worked on by) the Creative Commoners

**Comment by robbieaverill** [comment]
Bugs/things missed from the designs found while testing:

* https://github.com/silverstripe/silverstripe-versioned-admin/issues/35
* https://github.com/silverstripe/silverstripe-versioned-admin/issues/36
* https://github.com/silverstripe/silverstripe-versioned-admin/issues/37

**Comment by robbieaverill** [comment]
All PRs merged! 🎉
